### ISSUE TITLE
Simple Test

### ISSUE THREAD

**Issue by WANG-KX** [phuang17/DeepMVS#1]
Dear authors,
Thanks for your work and open source DeepMVS!
Is there a simple way to test the network on images with known intrinsic and extrinsic parameters but without colmap?
Thanks

**Comment by phuang17** [comment]
Unfortunately, I don't have codes ready for such applications. You can take a look at generate_volume_train.py to see how to generate the plane-sweep volume without COLMAP. 

Below are several problems you may encounter if you choose not to use COLMAP:
1. For a reference image, how should the neighbor images be selected?
2. For a reference image, how should its maximum disparity be estimated?

**Comment by phuang17** [comment]
Closing this issus as I do not have plan to support that. Please feel free to leave further comments if having more questions. Thanks.
