### ISSUE TITLE
Could you please share how to extract data from GTA to build dataset ?

### ISSUE THREAD

**Issue by chenchr** [phuang17/DeepMVS#10]

**Comment by phuang17** [comment]
I have been wanting to release the codes, but have not had time to do so :cry: Will probably spend my Thanksgiving weekend finishing that. For now, I can point you to [RenderDoc](https://renderdoc.org/), the main tool I used to captured the data. You can extract the depth buffer using that and even write scripts to make the capturing process automated.

**Comment by chenchr** [comment]
Thanks you !
