### ISSUE TITLE
RuntimeError: inconsistent tensor size

### ISSUE THREAD

**Issue by fasogbon** [phuang17/DeepMVS#12]
Please, do you have any idea why I can run into problem of RuntimeError: inconsistent tensor size, expected tensor [100 x 3 x 128 x 128] and src [100 x 3 x 112 x 128] to have the same number of elements, but got 4915200 and 4300800 elements. I am new to this field. See below :

Reloaded modules: colmap_helpers, generate_volume_test, model
<ipykernel.iostream.OutStream object at 0x0000024E05AE5438> Loading the trained model...
<ipykernel.iostream.OutStream object at 0x0000024E05AE5438> Successfully loaded the trained model.
<ipykernel.iostream.OutStream object at 0x0000024E05AE5438> Loading the sparse model...
<ipykernel.iostream.OutStream object at 0x0000024E05AE5438> Successfully loaded the sparse model.
<ipykernel.iostream.OutStream object at 0x0000024E05AE5438> Creating VGG model...
<ipykernel.iostream.OutStream object at 0x0000024E05AE5438> Successfully created VGG model.
<ipykernel.iostream.OutStream object at 0x0000024E05AE5438> Start working on image 0/3.
<ipykernel.iostream.OutStream object at 0x0000024E05AE5438> Working on patch at row = 0/3 col = 0/4
<ipykernel.iostream.OutStream object at 0x0000024E05AE5438> Working on patch at row = 0/3 col = 1/4
<ipykernel.iostream.OutStream object at 0x0000024E05AE5438> Working on patch at row = 0/3 col = 2/4
<ipykernel.iostream.OutStream object at 0x0000024E05AE5438> Working on patch at row = 0/3 col = 3/4
<ipykernel.iostream.OutStream object at 0x0000024E05AE5438> Working on patch at row = 1/3 col = 0/4
<ipykernel.iostream.OutStream object at 0x0000024E05AE5438> Working on patch at row = 1/3 col = 1/4
<ipykernel.iostream.OutStream object at 0x0000024E05AE5438> Working on patch at row = 1/3 col = 2/4
<ipykernel.iostream.OutStream object at 0x0000024E05AE5438> Working on patch at row = 1/3 col = 3/4
<ipykernel.iostream.OutStream object at 0x0000024E05AE5438> Working on patch at row = 2/3 col = 0/4
Traceback (most recent call last):

  File "<ipython-input-39-2662dfeab56e>", line 1, in <module>
    runfile('C:/Users/.../Desktop/DeepMVS-master/python/test.py', wdir='C:/Users/..../Desktop/DeepMVS-master/python')

  File "C:\Users\....\deepMVS2\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 668, in runfile
    execfile(filename, namespace)

  File "C:\Users\....\deepMVS2\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/..../Desktop/DeepMVS-master/python/test.py", line 253, in <module>
    data_in_tensor[0, 0, :, 0, ...] = ref_img_tensor.expand(num_depths, -1, -1, -1)

RuntimeError: inconsistent tensor size, expected tensor [100 x 3 x 128 x 128] and src [100 x 3 x 112 x 128] to have the same number of elements, but got 4915200 and 4300800 elements respectively at c:\anaconda2\conda-bld\pytorch_1519492996300\work\torch\lib\th\generic/THTensorCopy.c:86

**Comment by fasogbon** [comment]
Or can you please provide a test examples (with the txt file exports from colmap) thanks

**Comment by phuang17** [comment]
Can you print out `image_width` and `image_height` in test.py? Do they match the actual image size?

**Comment by fasogbon** [comment]
Yes the image height and width match! Even earlier I tested your approach setting image width to -1

**Comment by fasogbon** [comment]
See the attached images, i dont see any issue with the image_width and image_height
![error1](https://user-images.githubusercontent.com/38074103/48136316-09b46300-e2a8-11e8-8aed-420a648a8257.PNG)
![error2](https://user-images.githubusercontent.com/38074103/48136324-0e791700-e2a8-11e8-8046-9d4dccea3420.PNG)

**Comment by fasogbon** [comment]
![err3](https://user-images.githubusercontent.com/38074103/48349411-e6652b80-e68c-11e8-9db0-333aa4b56411.PNG)

Yes its strange! see theattached screenshot

**Comment by fasogbon** [comment]
- current start_y should be next_start_y from previous loop which is 128 but for weird reason its taking it as 112

**Comment by fasogbon** [comment]
Thank you for your feedback. My problem is eventually solved.

- It was due to conversion issue between python 2.7 and 3.5
- mismatch of int and float
- use of round vs int(container)

**Comment by phuang17** [comment]
Glad that you resolved it! And yes, my codes are for Python 2.7. Sorry about this limitation.
