### ISSUE TITLE
The create of MVS-Synth dataset

### ISSUE THREAD

**Issue by rann1018** [phuang17/DeepMVS#16]
Hi,

Thanks for your work and open-source MVS-Synth dataset.
I read your paper and am aware that you created this dataset from GTA5. However, how can you get the ground truth disparity maps, and the extrinsic and intrinsic camera parameters. I love this game but I think it can only capture images or videos.  Hope you can lend me some advice.

Thanks a lot.

**Comment by phuang17** [comment]
@rann1018 I used [RenderDoc](https://renderdoc.org/) to access the Z-buffer, which can then be converted to depth maps. The extrinsic and intrinsic camera parameters can also be computed by the model-to-world matrix and the model-to-world-to-view matrix withing the RenderDoc buffer results. It will require some knowledge about Computer Graphics. Please let me know if you have any other questions. Thanks!
