### ISSUE TITLE
Question on test evaluation

### ISSUE THREAD

**Issue by MASTERCHIEF343** [phuang17/DeepMVS#19]
Hi, thanks to your work.It's great.
I just wonder if I want to evaluate the DeMoN test datasets, how can I test it more efficiently.I see in your test instructions, I need to calculate the camera parameters again.But for DeMoN test datasets, all the parameters are provided.So have you used the provided camera parameters?

**Comment by phuang17** [comment]
Yes, I used the provided camera parameters, if I remember it correctly. You can write a script to convert the camera parameters to COLMAP's format.
