### ISSUE TITLE
About calculate photometric errors

### ISSUE THREAD

**Issue by tiffany61706** [phuang17/DeepMVS#3]
Dear authors,
Thanks for your work and open source of DeepMVS!
I was wondering that in your paper you mentioned about how to calculate photometric and geometric errors, but I couldn't find it in your code.
How did you calculate both of them? 
Thanks

**Comment by phuang17** [comment]
At current stage, I have not provided the codes for quantitative evaluation yet. Nevertheless, thanks for the reminder and I think it makes sense to add those codes. I will probably add them in mid-June.

**Comment by tiffany61706** [comment]
Thank you for your prompt reply. I am looking forward to your update. 
By the way, I have downloaded the ground truth of ETH3D dataset from your website. 
In your test code, you has ranged the disparity value into [0,1] to form into a output disparity image. 
And I use the same way to output the result as well and my image looks like grayscale image. 
Have you done any modification to let your images look like rgb image? 
Or you rearranges the value of disparity?
Thanks again

**Comment by phuang17** [comment]
I used the "viridis" colormap from matplotlib for disparity map visualization. Please refer to: https://matplotlib.org/examples/color/colormaps_reference.html
