### ISSUE TITLE
download_training_datasets.py

### ISSUE THREAD

**Issue by niatzt** [phuang17/DeepMVS#5]
When I run 'download_training_datasets.py', it shows an error 'ValueError: Could not load bitmap "<bytes>": LibRaw : failed to open input stream (unknown format)' due to the line:

img = imageio.imread(img.tobytes(), format = "RAW-FI")

after changed to:

img = imageio.imread(img.tobytes())

The code does not show any error; Not sure whether the change would cause problem for training.

**Comment by phuang17** [comment]
This problem actually troubles me a lot. Some people said that adding `format = "RAW-FI"` gives the error, but some said it gives the error **without** that. :confused:
Could you file a pull request which removes that argument? We can collect more feedback there and keep track of this issue. Thanks!

**Comment by niatzt** [comment]
I run the code with **format = "RAW-FI"** on another machine, this time it works fine. I guess you may need to comment on that line -- Depending on the machine, one may or may not need to use the format.

Besides, I modified the batch size whose default size is 1 in 'train.py'. It always report error claiming tensor size does not match.

**Comment by phuang17** [comment]
Thanks, @niatzt . I will add the comments when I have time.

**Comment by phuang17** [comment]
Resolved by #8 . Closing this issue.
