### ISSUE TITLE
Question: Performance vs COLMAP or OpenMVS?

### ISSUE THREAD

**Issue by snowzurfer** [phuang17/DeepMVS#7]
What is the performance compared to COLMAP or OpenMVS in outputting the depth maps?

**Comment by pmoulon** [comment]
You can find some comparison there: https://www.tanksandtemples.org/leaderboard/

**Comment by snowzurfer** [comment]
Thanks @pmoulon ; do you have any info about the performance of this specific repo? They seem to mention that it runs slowly, but don't quantify by how much.

**Comment by phuang17** [comment]
Hi @snowzurfer , I did not optimize the speed at all, so you can expect that the provided codes here run pretty slowly. From my experience, it takes approximately10x the time of COLMAP. However, there are a ton of places where things can be sped up. For example, I was generating the plane-sweep volume purely on CPU, and this could have been done using a GPU or at least multiple threads.

**Comment by snowzurfer** [comment]
@phuang17 Thanks for the explanation, makes sense. I will take a look into that
