### ISSUE TITLE
Results of trained model

### ISSUE THREAD

**Issue by whieya** [phuang17/DeepMVS#9]
I've tried on ETH3D dataset with provided trained model, and I got similar but different results, especially with more errors. 

I followed the instructions, and conducted sparse reconstruction via colmap. 

But the result seems include more errors such as belows. 

It's a result of facade in ETH3D benchmark. 
![image](https://user-images.githubusercontent.com/37824754/45018464-209ac700-b065-11e8-8a16-eeccbc297a51.png)

![image](https://user-images.githubusercontent.com/37824754/45018842-dcf48d00-b065-11e8-9f7c-6c99bf4fc7ce.png)

Most of huge errors are in sky region, even though I included MVS-SYNTH dataset in training.  

So I've trained the model myself but still I got similar errors and I don't know why. 

Is it because of colmap? or am I missing something?

**Comment by phuang17** [comment]
How did you run the sparse reconstruction? Did you run the sparse reconstruction again, or did you use the sparse reconstruction provided from [ETH3D's website](https://www.eth3d.net/datasets)? I was using the provided one, and I would guess that it led to better results.

**Comment by whieya** [comment]
Thanks for answering! 
I was running the sparse reconstruction again. I got better result with provided one.
